### PR TITLE
Remove diagram stuff

### PR DESCRIPTION
**Pull request by bjz**

### CODE REVIEW

**Comment by bvssvni** [comment]
Looks good. Could replace it with an image generated by "cargo-dot" https://github.com/maxsnew/cargo-dot

**Comment by kvark** [comment]
We'll need some kind of architecture overview anyway. I don't mind removing this one, but just curious - what is the motivation?

**Comment by bvssvni** [comment]
The old diagram was hand created, if I remember correctly.

Merging.

**Comment by bjz** [comment]
Yeah, it was out of date, and hard to keep up to date.

**Pull request merged**
