### PR TITLE
Moved all the handles into a separate module

### PR DESCRIPTION
**Pull request by kvark**
Our `device/lib.rs` became a bit overloaded, so I decided to move the handles out.

### CODE REVIEW

**Comment by bvssvni** [comment]
Maybe these could be reexported in "device/lib.rs"?

**Comment by bvssvni** [comment]
I think we should merge this and deal with naming and reexport in separate issues.

**Comment by kvark** [comment]
@bvssvni everything is re-exported in `gfx/lib.rs`. It is compatible with all the user code, just `gfx_device_gl` needs to be updated (https://github.com/gfx-rs/gfx_device_gl/pull/8)

**Comment by bvssvni** [comment]
Can I merge this?

**Comment by kvark** [comment]
I think so ;)

**Comment by bvssvni** [comment]
Nice!

**Pull request merged**
