### PR TITLE
Optional TextureKind Paramter to Texture Update

### PR DESCRIPTION
**Pull request by lynks--**

### CODE REVIEW

**Comment by kvark** [comment]
Looks good! Please squash it into a single commit.

**Comment by kvark** [comment]
Why did you use `Option<&tex::TextureKind>` instead of `Option<tex::TextureKind>`? I believe the indirection is not needed there, the type implements `Copy`.

**Comment by lynks--** [comment]
Yeah as you can see I got into a mess re commits after losing track. I'll rebase and squash. Also, yep not sure why I used a reference like that, I'll remove it. Come back in 20 mins! :)

**Comment by kvark** [comment]
Thanks!

**Pull request closed without merging**
