### PR TITLE
Resource Factory

### PR DESCRIPTION
**Pull request by kvark**
(ready now)

~~Includes #631~~
Paves the way to #570 

Moves all resource-related methods into `Factory`.
Cleans up `device/lib.rs` to be perfectly readable now!

### CODE REVIEW

**Comment by kvark** [comment]
The problem appears to come from `DeviceExt`, which is declared as follows:
```rust
pub trait DeviceExt<D: device::Device>: device::Factory<D::Resources> {..}
```
And then implemented as:
```rust
impl<D: device::Device, F: device::Factory<D::Resources>> DeviceExt<D> for F {..}
```

So, basically, I want it to be automatically implemented for any resource factory. The caveat is that it also needs a `CommandBuffer` type for `create_renderer`. One thing to try would be to implement it for any device that is also a factory. While this is more restricting, it would at least allow us to proceed with the change while not breaking everything.

Idea? Or maybe someone is willing to fix it?
cc @bjz @csherratt @bvssvni

**Comment by bvssvni** [comment]
The `Ext` convention is usually used for traits that inherit the trait, so `DeviceExt` would lead users to believe it inherits `Device`.

**Comment by kvark** [comment]
The inheritance itself is not important here. The fact is - `SomethingExt` gets auto-implemented for `Something` and extends the functionality using methods from `Something`. That's what we do with `DeviceExt`. The change only makes it to extend a `Factory` instead of `Device`, but given that `GlDevice` implements both, this should work for a short term.

**Comment by bvssvni** [comment]
I think we all agree we want to move in this direction, so I'll merge. Looks good.

**Comment by kvark** [comment]
Thanks @bvssvni ! I hope everyone had a chance to look at it.

**Pull request merged**
