### PR TITLE
Add log parameter to link_program

### PR DESCRIPTION
**Pull request by mninja**
As per the discussion on gitter about #656, here's a solution using Option<&mut String>.

### CODE REVIEW

**Comment by kvark** [comment]
Thanks for the PR!

Ok, `create_program` and `link_program` look good. But what about shaders? Often, the error you'd really want to see is the one from shader compilation, not the linkage.

Sorry for making this concern so late, it only hit me now.

**Comment by mninja** [comment]
That's a good point, but then how should it work? The same buffer can be extended and reused but then there's no easy way to differentiate where the errors come from.

**Comment by kvark** [comment]
Sorry, still don't have the answer. The simplest way would be to pass `Options<&mut [String]>`, where the first N strings will match give N shaders, and the last one is for the program.

**Comment by kvark** [comment]
Actually, there is a better way. We can abstract it like this:
```rust
trait ShaderErrorSink {
   fn compile(&mut self, &str);
   fn link(&mut self, &str);
}

impl ShaderErrorSink for () {...} //do nothing
impl ShaderErrorSink for String {...} //accumulate
impl ShaderErrorSink for &mut [String] {...} //keep separate logs
```
This is flexible, allows less noisy user syntax (`()` instead of `None`, and just something instead of `Option<something>`).

**Comment by mninja** [comment]
But then we would always query the log, or is there to match on the impl of ShaderErrorSink?

**Comment by kvark** [comment]
Ah, bummer :(

Regards,
Dzmitry

**Comment by bvssvni** [comment]
Closing because outdated.

**Pull request closed without merging**
