### PR TITLE
Use draw_state library

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/gfx-rs/gfx-rs/issues/603

### CODE REVIEW

**Comment by bvssvni** [comment]
Notice renaming of `CullMode => CullFace` and `WindingOrder => FrontFace`.

**Comment by kvark** [comment]
:+1: I'll refactor `bind()` method later, it shouldn't be blocking this PR.

**Comment by kvark** [comment]
Thanks!

**Comment by bjz** [comment]
Nice.

**Pull request merged**
